services:
  app:
    build: .
    container_name: equipment_observer
    ports:
      - "3001:3001" # port h√¥te : port conteneur
    volumes:
      - ./data.json:/app/data.json
      - ./public:/app/public
    restart: always
