services:
  app:
    build: .
    container_name: equipment_observer
    ports:
      - "3000:3000" # hostport:containerport
    volumes:
      - equipment_data:/app/data
      - equipment_thumbnails:/app/public/thumbnails
    restart: always

volumes:
  equipment_data:
  equipment_thumbnails:
